from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, DateTime, func, BigInteger, Integer, String, Numeric, Text

Base = declarative_base()


class DjBjdrgst(Base):
    __tablename__ = "dj_bjdrgst"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    house_platform_id = Column(BigInteger, nullable=True)
    mgm_bldrgst_pk = Column(String(20), nullable=True)
    pnu_cd = Column(Text)
    rnum = Column(Integer)
    plat_plc = Column(String(255))
    sigungu_cd = Column(String(5))
    bjdong_cd = Column(String(5))
    plat_gb_cd = Column(String(1))
    bun = Column(String(4))
    ji = Column(String(4))
    regstr_gb_cd = Column(String(5))
    regstr_gb_cd_nm = Column(String(50))
    regstr_kind_cd = Column(String(5))
    regstr_kind_cd_nm = Column(String(50))
    new_plat_plc = Column(String(255))
    bld_nm = Column(String(255))
    bylot_cnt = Column(Integer)
    na_road_cd = Column(String(20))
    na_bjdong_cd = Column(String(20))
    na_ugrnd_cd = Column(String(5))
    na_main_bun = Column(String(10))
    na_sub_bun = Column(String(10))
    dong_nm = Column(String(255))
    main_atch_gb_cd = Column(String(5))
    main_atch_gb_cd_nm = Column(String(50))
    plat_area = Column(Numeric(12, 3))
    arch_area = Column(Numeric(12, 3))
    bc_rat = Column(Numeric(12, 3))
    tot_area = Column(Numeric(12, 3))
    vl_rat_estm_tot_area = Column(Numeric(12, 3))
    vl_rat = Column(Numeric(12, 3))
    strct_cd = Column(String(5))
    strct_cd_nm = Column(String(100))
    etc_strct = Column(String(255))
    main_purps_cd = Column(String(5))
    main_purps_cd_nm = Column(String(100))
    etc_purps = Column(String(255))
    roof_cd = Column(String(5))
    roof_cd_nm = Column(String(100))
    etc_roof = Column(String(255))
    hhld_cnt = Column(Integer)
    fmly_cnt = Column(Integer)
    heit = Column(Numeric(12, 3))
    grnd_flr_cnt = Column(Integer)
    ugrnd_flr_cnt = Column(Integer)
    ride_use_elvt_cnt = Column(Integer)
    emgen_use_elvt_cnt = Column(Integer)
    atch_bld_cnt = Column(Integer)
    atch_bld_area = Column(Numeric(12, 3))
    tot_dong_tot_area = Column(Numeric(12, 3))
    indr_mech_utcnt = Column(Integer)
    indr_mech_area = Column(Numeric(12, 3))
    oudr_mech_utcnt = Column(Integer)
    oudr_mech_area = Column(Numeric(12, 3))
    indr_auto_utcnt = Column(Integer)
    indr_auto_area = Column(Numeric(12, 3))
    oudr_auto_utcnt = Column(Integer)
    oudr_auto_area = Column(Numeric(12, 3))
    pms_day = Column(String(8))
    stcns_day = Column(String(8))
    use_apr_day = Column(String(8))
    pmsno_year = Column(String(8))
    pmsno_kik_cd = Column(String(20))
    pmsno_kik_cd_nm = Column(String(100))
    pmsno_gb_cd = Column(String(20))
    pmsno_gb_cd_nm = Column(String(100))
    ho_cnt = Column(Integer)
    engr_grade = Column(String(20))
    engr_rat = Column(Numeric(12, 3))
    engr_epi = Column(Numeric(12, 3))
    gn_bld_grade = Column(String(20))
    gn_bld_cert = Column(Integer)
    itg_bld_grade = Column(String(20))
    itg_bld_cert = Column(Integer)
    crtn_day = Column(String(8))
    rserthqk_dsgn_apply_yn = Column(String(5))
    rserthqk_ablty = Column(String(100))
    created_at = Column(
        DateTime,
        nullable=False,
        server_default=func.now()
    )